language: android
dist: trusty

before_install:
  - chmod +x gradlew
  - mkdir "$ANDROID_HOME/licenses" || true
  - cp ./licenses/* "$ANDROID_HOME/licenses/"
  - ./gradlew dependencies || true

env:
  global:
    - ANDROID_API=28
    - EMULATOR_API_LEVEL=21
    - ANDROID_BUILD_TOOLS=28.0.6
    - ANDROID_ABI=google_apis/armeabi-v7a
    - ANDROID_TAG=google_apis
    - ADB_INSTALL_TIMEOUT=10 # minutes

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - android-$EMULATOR_API_LEVEL
    - extra-google-m2repository
    - extra-android-m2repository # for design library
    - addon-google_apis-google-19 # google play services
    - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL


before_script:
  - echo no | android create avd --force -n test -t "android-"$EMULATOR_API_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &


script:
  - "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"
